package Q2;

public class Developer extends Employee {
    private final String programming_lang;
   public Developer(String name, String address, int Salary, String job_title, String programming_lang){
        super(name, address, Salary,job_title);
        this.programming_lang=programming_lang;
    }

    public  String getProgramming_lang(){
        return programming_lang;
    }

    @Override
    public double calculating_Bonus() {
        return getSalary()*0.10;
    }


    @Override
    public String generating_performance_reports(){
        return "Reports are generated by "+name;
    }

    @Override
    public String  managing_projects(){
        return "Managing project -->"+name;
    }
    public void writeCode() {
        // Printing a message indicating the developer is writing code
        System.out.println("Developer " + name+ " is writing code in " + programming_lang);
    }

}
